apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadtago2683-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadtago2683-tenant-component
    app.kubernetes.io/part-of: loadtago2683-tenant-app
  name: loadtago2683-tenant-component
  namespace: loadtago2683-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadtago2683-tenant-component
    weight: null
status: {}
