apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadtago2683-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadtago2683-tenant-component
    app.kubernetes.io/part-of: loadtago2683-tenant-app
  name: loadtago2683-tenant-component
  namespace: loadtago2683-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadtago2683-tenant-component
status:
  loadBalancer: {}
